title: Dr. Ben Brewster
description: Hi! I'm a researcher doing work around modern slavery and human trafficking. Sometimes i do work on other crime and security issues too.
show_downloads: false
google_analytics: UA-81127361-1
theme: jekyll-theme-minimal
